name: 'React Native Version'
description: 'Composite Action for React Native Version Bump and GitHub Release'
author: 'Nabeel Shakeel'
branding:
  icon: check-circle
  color: blue

inputs:
  repo_token:
    description: "GitHub secret token"
    required: true
  supported_parameters:
    description: "A key-value pair of supported parameters"
    required: false
    default: '{}'
  
runs:
  using: "composite"
  steps:
    - name: Parse supported parameters
      id: json-input
      run: |
        # Using @actions/core package to use the fromJson function
        npm install @actions/core

        # Parsing the JSON input parameter
        inputs=$(echo "${{ inputs.supported_parameters }}" | npx @actions/core/lib/parser.js -j)

        # Output the parsed parameter value as a JSON string
        echo "::set-output name=inputs::$(echo "$inputs" | jq -r '.')"
      shell: bash

    - name: Automated Version Bump
      uses: paramsinghvc/gh-action-bump-version@master
      env:
        GITHUB_TOKEN: ${{ inputs.repo_token }}
      with:
        tag-prefix: ${{ steps.json-input.outputs.inputs.tag-prefix }}
        tag-suffix: ${{ steps.json-input.outputs.inputs.tag-suffix }}

    - name: Sync React Native version with package.json Version
      run: npx react-native-version
      shell: bash

    - name: Commit Version Sync Changes
      uses: EndBug/add-and-commit@v9
      with:
        message: ${{ github.event.inputs.commit-message }}

    - name: Create Automated Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ inputs.repo_token }}
        automatic_release_tag: ${{ steps.json-input.outputs.inputs.automatic_release_tag }}